### ISSUE TITLE
Verify team shared collections works

### ISSUE THREAD

**Issue by carlowahlstedt** [carlowahlstedt/NewmanPostman_VSTS_Task#11]
As [explained here](https://github.com/postmanlabs/newman/issues/273#issuecomment-240711863), verify the extension can handle team shared collections.

**Comment by sebcaps** [comment]
@carlowahlstedt  OK since #49 (more specifically 8c81ec015255ee198547491fa0ae7d8c23f7d7f3 ) ;-)
