### ISSUE TITLE
garbled letter

### ISSUE THREAD

**Issue by takuyaokamoto11** [carlowahlstedt/NewmanPostman_VSTS_Task#12]
I encountered this issue, after running the newman got a garbled letter.  
<img width="926" alt="screen shot 2018-02-12 at 9 19 46 am" src="https://user-images.githubusercontent.com/13827579/36079401-711d4e76-0fd6-11e8-9158-4c9e171f2b58.png">

and my setting is
<img width="670" alt="screen shot 2018-02-12 at 9 21 43 am" src="https://user-images.githubusercontent.com/13827579/36079404-7b438ba4-0fd6-11e8-8f5d-970b38e58186.png">

thanks, in advance

**Comment by carlowahlstedt** [comment]
It looks like you're not actually using the task that's built, but just the command line. If you'd like to use the task, then please use [the marketplace extension page](https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman) to install it.

Thanks.
