### ISSUE TITLE
VSTS Marketplace listing Q&A section URL to GitHub repo needs to be updated

### ISSUE THREAD

**Issue by PaulMEdwards** [carlowahlstedt/NewmanPostman_VSTS_Task#13]
The VSTS Marketplace listing Q&A section has a link to the GitHub repository for the extension. Unfortunately, that link is 404 as it seems the repo was renamed and the link didn't get updated...

Might want to fix that. ;)

[https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman#qna](https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman#qna)

**Comment by carlowahlstedt** [comment]
Thanks for the contribution!

No where in the exist task or extension json files do I see this referenced improperly. Need to figure out how that URL is being determined.

**Comment by carlowahlstedt** [comment]
Resolved
