### ISSUE TITLE
Request for Data binding option in the VSTS task

### ISSUE THREAD

**Issue by hitcl08** [carlowahlstedt/NewmanPostman_VSTS_Task#20]
Hi there,

Are there any plans to include a data binding option to the VSTS task so that csv data can be bound to the newman task similar to:

http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/

Currently the Newman command to implement data binding is something like:
>Newman run {collectionName} -e {environmentName} -d {data.csv}

It would save having to use a PowerShell script for this step. 

Thanks,

Liam 👍

**Comment by carlowahlstedt** [comment]
Have you tried v3 of the task?
<img width="372" alt="screen shot 2018-03-06 at 8 38 34 am" src="https://user-images.githubusercontent.com/2687687/37035219-d0ae8b30-2119-11e8-844b-c0bf51318701.png">

It has a data option which I think it what you're looking for.
<img width="160" alt="screen shot 2018-03-06 at 8 38 26 am" src="https://user-images.githubusercontent.com/2687687/37035227-db627eb0-2119-11e8-9929-fe2646096d63.png">

**Comment by hitcl08** [comment]
Ah yes I see.

Problem solved!

Thank you again!
