### ISSUE TITLE
Undefined error after a successful run of the newman task

### ISSUE THREAD

**Issue by cfs77** [carlowahlstedt/NewmanPostman_VSTS_Task#22]
Hi,

after a successful run of the task (junit test output is generated) I get the following error message:

2018-03-07T13:40:39.5316103Z ##[section]Starting: Newman - Postman
2018-03-07T13:40:39.5316103Z ==============================================================================
2018-03-07T13:40:39.5316103Z Task         : Newman the cli Companion for Postman
2018-03-07T13:40:39.5316103Z Description  : Using Newman, one can effortlessly run and test a Postman Collections directly from the command-line. Now in a task!
2018-03-07T13:40:39.5316103Z Version      : 3.0.4
2018-03-07T13:40:39.5316103Z Author       : Carlo Wahlstedt
2018-03-07T13:40:39.5316103Z Help         : [More Information](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/blob/master/README.md)
2018-03-07T13:40:39.5316103Z ==============================================================================
2018-03-07T13:40:40.0315995Z found 1 files
2018-03-07T13:40:40.1097247Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\Users\TFSSERVICE\AppData\Roaming\npm\newman.cmd run --ssl-client-cert E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\r11\a --ssl-client-key E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\r11\a -r junit -n 2 -e "E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\r11\a\CAS Drive REST Service\PostmanFiles\DRI-WIN2016-03.postman_environment.json" "E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\r11\a\CAS Drive REST Service\PostmanFiles\REST Service.postman_collection.json""
**2018-03-07T13:41:17.1098040Z { code: 1, error: undefined, stdout: '', stderr: '' }
2018-03-07T13:41:17.1254323Z ##[error]Failed**
2018-03-07T13:41:17.1254323Z ##[section]Finishing: Newman - Postman

Do you have any idea about this topic?
Can I activate more logging?

Thanks for your help.

**Comment by carlowahlstedt** [comment]
@sebcaps any idea on this one? I did get the task to auto build and deploy to the marketplace. @cfs77 found an issue with that, but I corrected it yesterday in #21

**Comment by sebcaps** [comment]
Unfortunately, no ideas.
No yet updated in my side, I'll do it and let you know.
Sound strange that the report is generated and an error logged...

**Comment by cfs77** [comment]
Hi,

unlike issue #23 this problem is not gone with TFS2018

**Comment by carlowahlstedt** [comment]
I don't see any more possibilities for additional verbosity from newman itself. Code 1 is supposed to mean a failure in your test, but you said everything was successful? Can you post your junit test output?

**Comment by cfs77** [comment]
Hi,

below you will find a zip which contains the result xml. 
The picture shows the results on the release/test-hub

[newman-run-report-2018-03-15-08-08-34-015-0.zip](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/files/1814491/newman-run-report-2018-03-15-08-08-34-015-0.zip)

![image](https://user-images.githubusercontent.com/37112783/37451600-499a1cf2-2832-11e8-9e6b-4bc862849621.png)

**Comment by sebcaps** [comment]
@cfs77, did you try to run the command line ```C:\Windows\system32\cmd.exe /D /S /C "C:\Users\TFSSERVICE\AppData\Roaming\npm\newman.cmd run --ssl-client-cert E:\TFS-Build\vsts-agent-win7-x64-2.105.6_work\r11\a --ssl-client-key E:\TFS-Build\vsts-agent-win7-x64-2.105.6_work\r11\a -r junit -n 2 -e "E:\TFS-Build\vsts-agent-win7-x64-2.105.6_work\r11\a\CAS Drive REST Service\PostmanFiles\DRI-WIN2016-03.postman_environment.json" "E:\TFS-Build\vsts-agent-win7-x64-2.105.6_work\r11\a\CAS Drive REST Service\PostmanFiles\REST Service.postman_collection.json""``` outside TFS2018 , in a shell, updating path.
It can be an error raised by Newman itself, that does not prevent successful exec.

**Comment by cfs77** [comment]
Hi,

when the command run from a commandline the error isn't thrown and the test ouput file is successfully created.

![image](https://user-images.githubusercontent.com/37112783/37531256-ea515638-293b-11e8-9dd4-584cebfd441f.png)

So it should be an error in the task.

**Comment by carlowahlstedt** [comment]
@cfs77 not sure if this will fix your issue, but [had a thought](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/issues/25) that @sebcaps [executed on](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/pull/26) in regard to empty paths. Let us know if the update changes anything for you. If you don't mind posting the output again that would be great as well. Thanks.

**Comment by carlowahlstedt** [comment]
So...based on your logs, it looks like the reason it's failing is because of failed assertions. Your command line has 4 failed and your TFS has 6, but they are both failing. The task is setup so that if any of the tests fail, the task fails.

**Comment by sebcaps** [comment]
Agree with @carlowahlstedt, however JUNIT test report should report those error as well.
@cfs77  is junit report tests in fail status
It was stated first no error reported (cf screenshot of 2018/03/15) and error message displayed.
Anyway error message reported `2018-03-07T13:41:17.1098040Z { code: 1, error: undefined, stdout: '', stderr: '' }
2018-03-07T13:41:17.1254323Z ##[error]Failed` comes from newman and in my honest opinion not related to the task.

**Comment by cfs77** [comment]
Hi @carlowahlstedt / @sebcaps,
I fixed the failing tests and the error message disappers. 
That's a change to my inital mesage of this issue - thank you for your help.

![image](https://user-images.githubusercontent.com/37112783/38031021-87e7c6e0-329a-11e8-9e1a-d3b8b922ac19.png)

**Comment by Madhusudanpatidar** [comment]
Hi @carlowahlstedt / @sebcaps 
while running the pipeline using newman with postman collection

my Run API Test is successfuly run but below error msg is shown

![image](https://user-images.githubusercontent.com/46986603/81783373-ddbb1300-9518-11ea-9f9e-86e488722f3c.png)

**Comment by Madhusudanpatidar** [comment]
Hi @carlowahlstedt / @sebcaps
Plz help to associated postman test to devops test plan
and while running pipeline so **test plan state** is **pass and fail** is changed automatics
what is the logic behind it... plz share with me..

and i have already lookout the devops api to change state of devops test cases but how can **implement to devops pipeline with postman collection** 

Thanks in advance

**Comment by Madhusudanpatidar** [comment]
> Hi @carlowahlstedt / @sebcaps
> 
> 1. I have Postman api tests that run successfully in azure pipeline, I export results in jUnit format and publish them, the results are displayed properly.
> 
> I would like to associate my postman tests (written in Javascript) with Plans test cases.
> 
> I can't find a precise documentation about this case in general, there is a suggestion here that uses c# https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops
> 
> but i am using javascript. Is there a way to solve this ?
> 
> sorry for the missed out ticket, i can't say if this is an enhancement or a bug or a feature request
> 
> 
> while running the pipeline using newman with postman collection
> 
> my Run API Test is successfuly run but below error msg is shown
> 
> ![image](https://user-images.githubusercontent.com/46986603/81783373-ddbb1300-9518-11ea-9f9e-86e488722f3c.png)

Hi @carlowahlstedt / @sebcaps
Plz help to associated postman test to devops test plan
and while running pipeline so test plan state is pass and fail is changed automatics
what is the logic behind it... plz share with me..

and i have already lookout the devops api to change state of devops test cases but how can implement to devops pipeline with postman collection

Thanks in advance

**Comment by sebcaps** [comment]
@Madhusudanpatidar your request  to link postman to testplan is more likely a new feature. Please submit a new ticket, rather than using a closed one. Do not hesitate to point to availabl resources or better submit a PR.
For the second point, from what I see is that your test fail you have 3 assertions errors so, to me Fail status is "correct" . Why do you state it's passed ?

**Comment by Madhusudanpatidar** [comment]
> @Madhusudanpatidar your request to link postman to testplan is more likely a new feature. Please submit a new ticket, rather than using a closed one. Do not hesitate to point to availabl resources or better submit a PR.
> For the second point, from what I see is that your test fail you have 3 assertions errors so, to me Fail status is "correct" . Why do you state it's passed ?

So First point as per your point of you, right now is not implemented bcz its feature release of new version, Ok

Second point now thanks for updating me, got the solution..

**Comment by RanguBS** [comment]
@Madhusudanpatidar did you got solution this issue.. if so please share with me too
