### ISSUE TITLE
Configuration of the reporters option isn't possible

### ISSUE THREAD

**Issue by cfs77** [carlowahlstedt/NewmanPostman_VSTS_Task#23]
Hi, 

I found another small bug in the UI.

![image](https://user-images.githubusercontent.com/37112783/37137948-62460318-22a8-11e8-9df3-4560beaaa6fd.png)

**Comment by carlowahlstedt** [comment]
What version of TFS are you using? VSTS seems to render fine:

<img width="840" alt="screen shot 2018-03-08 at 11 23 18 pm" src="https://user-images.githubusercontent.com/2687687/37190437-bcf38fe0-2327-11e8-9925-0a1a89aaa1cb.png">

**Comment by cfs77** [comment]
@carlowahlstedt TFS2017.2

The error came with one of your newman task updates. Since I configured junit as a reporter in UI the TFS-Version hasn't changed. But now I can't changed the reporter anymore.

**Comment by carlowahlstedt** [comment]
Yes, we updated the task to be a dropdown list so that you can select the values instead of having to know what to type in.

I was asking about your version because the dropdown simply isn't showing for you. I need to do some research to see why, now that I know your TFS version.

**Comment by cfs77** [comment]
@carlowahlstedt Thank you. If you need more information. Please, let me know.

**Comment by carlowahlstedt** [comment]
I don't seem to see any reason it would be doing this. I tried putting some improper value in the v2 of the task, the change it to v3. That didn't break it. I was doing it on VSTS and not TFS. I don't have a 2017.2 install to test with. Maybe try to switch to v2, clear the field, and switch to v3? It might be a specific issue with TFS 2017.2.

The only other reference I found said you should look at the [Azure App Service Manage](https://github.com/Microsoft/vsts-tasks/issues/5122#issuecomment-325907668) task. The input is 'Install Extensions' and is visible when 'Action' = 'Install Extensions'. 

You could try to see if that is rendering properly.

For reference, this is what it should look like:
<img width="1025" alt="screen shot 2018-03-14 at 9 23 19 am" src="https://user-images.githubusercontent.com/2687687/37404927-a2e9e8b0-2769-11e8-9842-69f20a81fa5d.png">

**Comment by cfs77** [comment]
Hi,

it's not possible for me to change the version of the task. I only have version 3 available.

![image](https://user-images.githubusercontent.com/37112783/37418242-0e256562-27b2-11e8-9202-19d30dda8613.png)

How will I get version 2?

**Comment by cfs77** [comment]
Hi again,

I think we can close the issue. We are about to switching to TFS2018. On our preproduction machine of TFS2018 the dropdown appears.

![image](https://user-images.githubusercontent.com/37112783/37418728-2d55c1ec-27b3-11e8-8fcd-4c03e35afbe1.png)

Thank for your investigations.

**Comment by carlowahlstedt** [comment]
Good to know it was either your TFS version or setup. Either way, glad it's working for you now.
