### ISSUE TITLE
Support custom reporters

### ISSUE THREAD

**Issue by viperx77** [carlowahlstedt/NewmanPostman_VSTS_Task#30]
Allow adding additional custom reporter names in addition to the "Reporters" multi-select list.

**Comment by sebcaps** [comment]
@viperx77, can you elaborate your request : with custom reporter, name must be provided to Newman CLI.
So I guess it can be done only with additional params ie : existing select list + **new textbox to set reporter name**. 
Please submit PR if I'm not the right direction.

**Comment by viperx77** [comment]
Yes, correct.  Need additional parameters to be specified.

**Comment by sebcaps** [comment]
@viperx77 New param "customReport" added in configuration.
⚠️ task just add an argument value, no check for availability of the reporter code...
Please let me know if's OK. 
Very nice if you could share your experience with custom report config updating ReadMe.
thx

**Comment by carlowahlstedt** [comment]
This has been released. 

@viperx77 I'll second what @sebcaps said. It would be very helpful to the community to include some information in the ReadMe about custom report config. We've had several questions around reporting the past. Thanks.
