### ISSUE TITLE
EISDIR: illegal operation on a directory, on on-prime TFS

### ISSUE THREAD

**Issue by NileshMoradiya** [carlowahlstedt/NewmanPostman_VSTS_Task#35]
It's very handy Task and i was trying to use on on-prine TFS, and set configuration as below
![image](https://user-images.githubusercontent.com/4757071/41395230-91468060-6fca-11e8-9663-88bb7489fd75.png)
...
![image](https://user-images.githubusercontent.com/4757071/41395267-a5d8c8c6-6fca-11e8-8d63-5d1fb77722ae.png)
 and it's showing error as below

`EISDIR: illegal operation on a directory, open 'D:\GITDB-Build-1\_work\2\a'
error writing file "D:\GITDB-Build-1\_work\2\a" for junit-reporter
{ code: 1,
  error: undefined,
  stdout: 'error writing file "D:\\GITDB-Build-1\\_work\\2\\a" for junit-reporter\n',
  stderr: 'EISDIR: illegal operation on a directory, open \'D:\\GITDB-Build-1\\_work\\2\\a\'\n' }`

**NOTE:** It's working fine with manual command with newman _run "src\CBRE.GITDB.API.Test\PostmanCollections\Transaction.postman_collection.json" -e "src\CBRE.GITDB.API.Test\PostmanCollections\Transaction-DEV.postman_environment.json" -r html,cli,json,junit --reporter-junit-export  $(build.artifactstagingdirectory)/op.xml_

Is there any specific settings i'm missing?

#happydevelopment

**Comment by carlowahlstedt** [comment]
@NileshMoradiya could you give us the information needed here or can we otherwise close this?
