### ISSUE TITLE
Reports: Make sure the result format of the file 'newman-run-report-*.xml' matches 'JUnit' test results format

### ISSUE THREAD

**Issue by MackeyG** [carlowahlstedt/NewmanPostman_VSTS_Task#38]
Hello, I have just setup the plugin and am struggling with reports. I see the below log line for each of the collections run by the Newman Task.

2018-09-19T18:47:49.6701617Z ##[warning]Invalid results file. Make sure the result format of the file '/datadrive/myagent/_work/r1/a/newman/newman-run-report-2018-09-19-18-47-28-154-0.xml' matches 'JUnit' test results format

**Publish Test Results Setup:**
![image](https://user-images.githubusercontent.com/43078281/45774805-f7a93300-bc1b-11e8-8ed2-3d6b912bdb73.png)

**Newman Task Setup-:**
![image](https://user-images.githubusercontent.com/43078281/45774846-190a1f00-bc1c-11e8-8be3-ea191efc0459.png)
**The only other field I have populated is Reporters, it is set to Junit**

**Comment by carlowahlstedt** [comment]
After specifying junit, it will output a file. If you don't give it a directory then as the help says:

> Specify a path where the output JUnit file will be written to disk. If not specified, the file will be written to newman/ in the current working directory.

I don't have a good example of this setup, so maybe @sebcaps can give a more solid example, but you should be able to look at your output log to see what the junit file it is generating and then point your publish task at that folder.

**Comment by MackeyG** [comment]
I can confirm the file is being found. In one of my first attempts I received the following warning when the file was not found "##[warning]No test result files matching **/newman/TEST-*.xml were found.",

I have gone back to using a command line task with the same arguments. All works well.

**Comment by didaskein** [comment]
Maybe it could come from the xml file format : https://developercommunity.visualstudio.com/content/problem/424608/publish-test-results-no-build-level-attachments-to.html   

> the newman didn't contain the testcases xml element and because of this the publish of the tests didn't work. 

Junit Format : 
https://www.ibm.com/support/knowledgecenter/fr/SSQ2R2_9.1.1/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html

I have the same issue, i'm able to produce an xml file but it's not visible in the Tests case un Azure DevOps

i have an xml like this: 
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Api v1.0" tests="1" time="2.000">
  <testsuite name="Release / Reinint blob" id="ff2192bb-052f-4c4f-9e1b-4122b6a41116" timestamp="2019-05-29T16:26:52.209Z" tests="0" failures="0" errors="0" time="1.000"/>
</testsuites>
```

Maybe we need a <testcase> in the xml generated by newman ? 

thank you

**Comment by didaskein** [comment]
I found the solution : You need to ### Add Test in your postman collection
![image](https://user-images.githubusercontent.com/13362276/58576478-b9e9b900-8244-11e9-9519-5530a4b1c6b4.png)
![image](https://user-images.githubusercontent.com/13362276/58576508-ccfc8900-8244-11e9-9d9d-b3d91a551cea.png)
=> No bug :) maybe add the fact that we need to add test in bold with a snapshot :)

Add test : https://medium.com/@arthurgomesfaria/automating-apis-testing-with-postman-and-newman-a9a9ef0354d4

**Comment by carlowahlstedt** [comment]
@didaskein to be clear, you're saying that [the suggested steps](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/#report) to output a report didn't work for you?
