### ISSUE TITLE
Misplaced quotes in command

### ISSUE THREAD

**Issue by scotty3** [carlowahlstedt/NewmanPostman_VSTS_Task#41]
Running this task on a Custom Build Agent, with file paths to newman.cmd, collection.json and environment.json specified. The generated command puts quotes in the wrong place resulting in a failure.

With Misplaced Quotes:
C:\Windows\system32\cmd.exe /D /S /C "C:\npm\newman.cmd run "C:\vstsagent\A1\_work\r2\a\_App 1.2\drop\bin\Release\test\app.postman_collection.json" -r junit -n 1 -e "C:\vstsagent\A1\_work\r2\a\_App 1.2\drop\bin\Release\test\app.postman_environment.json""

Should look like:
C:\Windows\system32\cmd.exe /D /S /C C:\npm\newman.cmd run "C:\vstsagent\A1\_work\r2\a\_App 1.2\drop\bin\Release\test\app.postman_collection.json" -r junit -n 1 -e "C:\vstsagent\A1\_work\r2\a\_App 1.2\drop\bin\Release\test\app.postman_environment.json"

Is there another way to specify my file paths to handle this situation?

**Comment by carlowahlstedt** [comment]
Sorry for the late reply.

[Looking at one of the examples](https://dev.azure.com/carlo/VSTS_Tasks/_releaseProgress?_a=release-environment-logs&releaseId=79&view=mine&environmentId=79), it looks like there aren't quotes around the path. Those should only be necessary if there's a space in the path (which then might cause an issue).

`[command]C:\Windows\system32\cmd.exe /D /S /C "C:\npm\prefix\newman.cmd run D:\a\r1\a\_carlowahlstedt_NewmanPostman_VSTS_Task\tsconfig.json -n 1 -e D:\a\r1\a\_carlowahlstedt_NewmanPostman_VSTS_Task\vss-extension.json"`

Did you maybe add quotes manually that you could take out?

**Comment by scotty3** [comment]
I resolved my problem by removing spaces in the original file path, which I found was different than the one in my example, thank you.
