### ISSUE TITLE
Stack Trace vs Error message in test results

### ISSUE THREAD

**Issue by antonGritsenko** [carlowahlstedt/NewmanPostman_VSTS_Task#42]
Hi all

We try to setup newman in our release pipeline and a bit lost. We have pretty nice and clear messages in the console, but in VSTS output looks like a mess.
First of all, error message is empty. To be honest, we did expect error message same like in the newman cli:

> expected response to have status code 200 but got 404
> at assertion:0 in test-script
> inside "Path \ In\ Collection"

The stack trace also a very useless: it's a single huge and long line of text where everything messed up and a lot of debug info (like internal script names and so on). 
![image](https://user-images.githubusercontent.com/16330285/48161310-481f4180-e2eb-11e8-893f-7e6c1e68d0cb.png)

Is it our config wrong or a test script wrong or by design?

**Comment by carlowahlstedt** [comment]
Seems like we're looking at a subset of your results here, but based on the text you've got a test that's running and not giving the expected http status code. 

Looking at your image it seems that call is /api/v1/User/Settings...

I'm not sure what you're looking for here exactly, as it seems the detail you have is enough to determine your failure?

**Comment by antonGritsenko** [comment]
@carlowahlstedt well, it's enough but they are very unstructured. Again, the first test is from newman cli, and it's clear and well structured. 

The screenshot above from VSTS (Azure DevOps) and information is no structured at all, it's hard to understand and hard to read. Why not to make it same as in newman cli?

**Comment by carlowahlstedt** [comment]
I think you might be confusing what this task does vs Azure DevOps vs Newman. This task can simply run Newman inside of Azure DevOps. So the test results that are produced for display are simply something that Newman does and Azure DevOps renders.

That said, there might be something that can be better generated here, but I can't say that I'm knowledgable enough to know that answer. If you're able to distinguish why it's doing what it's doing you might be able to either adjust the instructions in the repo here to better assist others, request and assist the Newman command line to generate a better output, or submit a bug request to Azure DevOps.

Hope this is helpful. I'm happy to assist in any way, and if you can show how to reproduce this somewhere, I'll be happy to look further, but without more information I'm afraid I don't have the resources to better assist.

**Comment by antonGritsenko** [comment]
Thanks for reply. Yeah, looks like its an issue in newman itself, it generate really strange XML output in case of junit format (use <![CDATA[ for each line). Usual thing for open sourced projects ))
Looks like we will go away from Postman.

**Comment by carlowahlstedt** [comment]
I'd encourage you to look into contributing to [Newman](https://github.com/postmanlabs/newman) or at least opening an issue over there. You're likely not the last person to notice this and wish it worked differently.
