### ISSUE TITLE
Remove mandatory environment file

### ISSUE THREAD

**Issue by relent0r** [carlowahlstedt/NewmanPostman_VSTS_Task#44]
Due to a limitation of newman the only way to pass variables in during run time in TFS is using global variables. 
When we trigger a collection and pass all variables in using tfs, no environment files are used.
It would be nice if the environment file was not mandatory as in this scenario its not required.

**Comment by carlowahlstedt** [comment]
Could you better layout the scenario here?
`Due to a limitation of newman the only way to pass variables in during run time in TFS is using global variables.`
Seems like you're saying it is Newman, but referencing TFS as well. Does TFS have anything to do with this or does Azure DevOps behave the same?

**Comment by relent0r** [comment]
Sorry let me better explain my scenario.

We are using TFS 2018 (renamed to Azure DevOps in Microsoft's wisdom) and I'm using newman during the release process to validate microservice functionality.
So during release we'll use one deployment group phase to deploy the application then we add an agent phase for performing postman testing on the microservice.
We've created postman collections for this but since we want to use variables from TFS we don't use an environment file.
To date I've just used the command line task and run newman via that using --global-variable $(variablenamehere) for each variable used in the postman collection. 
I saw your cli companion and thought it would be a more aesthetically pleasing way to do this for other team members rather than using command line task for this process. But it has a mandatory requirement for an environment file in the task configuration.

Hopefully this makes more sense.

**Comment by carlowahlstedt** [comment]
@relent0r this should be released now. Please verify for us.

**Comment by carlowahlstedt** [comment]
@relent0r there was an issue with the update of the task. I believe you should be able to specify none now and get what you need. Can you please let us know?

**Comment by relent0r** [comment]
Sorry for the late reply, yes this looks good with the none option thanks.
