### ISSUE TITLE
'Reporter JUnit Export' parameter requires that file already exists

### ISSUE THREAD

**Issue by 24mu13** [carlowahlstedt/NewmanPostman_VSTS_Task#48]
If I specify let's say **report.xml** as _Reporter JUnit Export_ parameter, this file should exits; otherwise the task will result in error.

The same invocation by CLI will work instead!

`newman run mycollection.json -r junit -n 1 -e myenv.json --reporter-junit-export=report.xml`

**Workaround**: place a task before, with following command, for instance:
`true > report.xml`

**Comment by sebcaps** [comment]
@24mu13  according to [NewMan doc](reporterJsonExport) this option expect a path and not a filename.
If not set the report will be generated to `newman/` in the current working directory.
To me not really a bug, but can you please share error message you get while specifying an unexisting file name ?

**Comment by esbenbach** [comment]
So I am experiencing the same issue. I am pointing the junit export file to a specific report location. The task uses `getPathInput` from the pipeline lib to determine if the path exists. However, according to the documentation, the file will be generated if it does not exist, so the supplied 'check' parameter to `getpathinput` is not needed.

From the newman docs (https://github.com/postmanlabs/newman#junitxml-reporter):  If the specified path does not exist, it will be created

**Comment by carlowahlstedt** [comment]
@esbenbach @24mu13 can either of you confirm that that PR #51 fixed this? Most recent version after some other fixes is 3.0.26.

**Comment by esbenbach** [comment]
On vacation currently, will confirm when i get back.

**Comment by esbenbach** [comment]
The change fixes the issue I had at least. It now creates the xml file without complaining.
