### ISSUE TITLE
Option to suppress exit code -x, --suppress-exit-code

### ISSUE THREAD

**Issue by Srinu3366** [carlowahlstedt/NewmanPostman_VSTS_Task#52]
Is there an option to suppress exit code 1 in case of test failures. We would like to use publish test results step to publish the failures and the fail the build in this test results. 

Current exit code error - 
##[error]The process '/usr/local/bin/newman' failed with exit code 1

Thanks,
Srini

**Comment by sebcaps** [comment]
@Srinu3366 this option is not currently supported, but not a Big deal to add it 😀
I'll see if I'll have time to do it, but maybe you could have a try?

**Comment by Srinu3366** [comment]
Continue on error option on control options is working as intended for this purpose. It will not fail the step and we can use publish test results as next to publish the result and fail if any error.

![image](https://user-images.githubusercontent.com/25985494/56508217-4b009e00-64e9-11e9-8fb3-0d2d41b9b81d.png)
