### ISSUE TITLE
Add newman-reporter-htmlextra as an output option

### ISSUE THREAD

**Issue by Scott-Emberson** [carlowahlstedt/NewmanPostman_VSTS_Task#56]
It would be great if you could add another output option of HTML extra (newman-reporter-htmlextra)

https://www.npmjs.com/package/newman-reporter-htmlextra

Scott

**Comment by sebcaps** [comment]
@Scott-Emberson  if my understanding is correct and according to [this](https://github.com/postmanlabs/newman#community-maintained-reporters), it should consist in :
- add `htmlextra` option in `task.json`
- handle this new option in `newmantask.ts`
For the moment I don't know how to ensure the lib is installed but I guess that a manual task  before NewmanPostman could do the trick...
Not too many time available for the moment to handle it, I'll try to, but  you could try submit a PR if need it urgently.

**Comment by carlowahlstedt** [comment]
Can't release this until #59 gets resolved.

**Comment by Scott-Emberson** [comment]
@carlowahlstedt do we know what version this will be in now we issue #59 has been resolved?

**Comment by yossarian123** [comment]
Ha, I had the change for this on a branch then I saw the issue already logged.  

When is this going to be released?

**Comment by carlowahlstedt** [comment]
This should be released. It went out when I pushed the update for the fixes postman requested.

**Comment by Scott-Emberson** [comment]
@carlowahlstedt I don't see any of the options available in the task. 
![image](https://user-images.githubusercontent.com/8268155/59012353-2f4e1e80-882f-11e9-95a5-0f95252fb74a.png)
The code does show.
`    {
      "name": "reporters",
      "type": "picklist",
      "label": "Reporters",
      "properties": {
        "MultiSelectFlatList": "True"
      },
      "options": {
        "cli": "cli",
        "json": "json",
        "html": "html",
        "htmlextra": "htmlextra",
        "junit": "junit"
      },
      "required": false,
      "helpMarkDown": "Format of report. Multi selection allowed.",
      "groupName": "report"
    },`

**Comment by carlowahlstedt** [comment]
hmm, I just checked and am seeing it. Sometimes the UI doesn't update the task immediately when it's not a minor version bump. The release currently auto increments the revision number. This has also been what I've experienced with an on-prem build server. Hosted seems to generally work (I believe there's a reason for that) Will you check again? If you don't see it, then I'll look at adjusting what the release increments.

![image](https://user-images.githubusercontent.com/2687687/59193685-81a37e00-8b54-11e9-85fc-85c31e14f8f9.png)

![image](https://user-images.githubusercontent.com/2687687/59193655-6d5f8100-8b54-11e9-8848-0b46c43930b1.png)

**Comment by Scott-Emberson** [comment]
@carlowahlstedt Yes, I found this out over the weekend for on-prem. The only way I have found to force the UI to update is to delete and install again. I can now see it. 

![image](https://user-images.githubusercontent.com/8268155/59194566-57b48080-8b81-11e9-810b-329c5c985862.png)


@yossarian123 if you're using an on-prem version go to
https://tfs.URL.com/tfs/_gallery/manage
Delete the extension
Wait a few minutes
Then go to the web page for the extension [https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman](URL)
Install it and then you see the UI change.

**Comment by carlowahlstedt** [comment]
OH, on prem installation, not just build server. Hmm, I think they would behave the same, but guess not. I'll look at changing the increment like mentioned. Then you can figure out later if that improves things.

Are we good to close this for now otherwise?

**Comment by carlowahlstedt** [comment]
that was easy enough. Next release will increment the minor version by default.
![image](https://user-images.githubusercontent.com/2687687/59214434-145c1100-8b85-11e9-974a-ffa804d9b358.png)
