### ISSUE TITLE
sslStrict value must be set to true to have --insecure option used

### ISSUE THREAD

**Issue by afeblot** [carlowahlstedt/NewmanPostman_VSTS_Task#58]
See your code:
```
let sslStrict = tl.getBoolInput('sslStrict');
newman.argIf(sslStrict, ['--insecure']);
```
The `--insecure` option is added to the newman command line when `sslStrict` is set to true. I assume it should be the opposite.

**Comment by sebcaps** [comment]
Thx for your input. But sslstric is the internal name of the variable. Maybe not optimal, but the aim as stated in user interface with label and help tooltip is to disable ssl verification, so  '--insecure' must be added when true. Hope it helps. Let me know if not 😀

**Comment by afeblot** [comment]
Hey ;-)
Actually, sslStrict is not purely internal, as it is used as a parameter key in the yaml form of the plugin. That makes it part of the public interface. And given the name, without further documentation, you would expect that if sslStrict is true, ssl is strict, so --insecure is not used.
I think you should do one of these, by other of preference:
* change the plugin code so that sslStrict=false triggers --insecure
* rename sslStrict to sslInsecure and keep the current behavior
* document very clearly which value leads to which result

**Comment by carlowahlstedt** [comment]
Thanks for your input @afeblot. I understand where you're coming from, but I would have to agree with @sebcaps that the variable name is actually internal to the task (the user does not experience this). That said, you have a valid point that the variable name could be improved, but the functionality is not broken.

We'll leave this open for someone to work on if they desire with the recommendation that the variable name be improved to more correctly match the action being performed.

**Comment by afeblot** [comment]
So, I created a PR for each of the first 2 solutions I proposed. Would you please chose one and reject the other?

**Comment by carlowahlstedt** [comment]
#60

**Comment by satano** [comment]
This issue can be closed, no? `sslStrict` was replaced with `sslInsecure`.
