### ISSUE TITLE
Extension is now unpublished from Marketplace.

### ISSUE THREAD

**Issue by cinmay** [carlowahlstedt/NewmanPostman_VSTS_Task#59]
The extension doesn't show up in the marketplace search and when I go directly to the extension page is says:
`This extension is now unpublished from Marketplace. You can choose to uninstall it.`

https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman&ssr=false#overview

**Comment by carlowahlstedt** [comment]
strange, I'll have to look into this

**Comment by carlowahlstedt** [comment]
I've tweeted at Azure DevOps.
https://twitter.com/carlowahlstedt/status/1130635166584586242

**Comment by carlowahlstedt** [comment]
Well, here you go. Postman actually had it taken down...https://twitter.com/carlowahlstedt/status/1130825635230879744

**Comment by Scott-Emberson** [comment]
That says it all @carlowahlstedt where do we go from here?

**Comment by carlowahlstedt** [comment]
Considering it's going to have to be republished to even work, I'm inclined to not deal with it. That said, there are obviously enough people interested in that task that I hate to see it die. What I'd really like to do is pull in more people to help with the direct management of things. @sebcaps has already done a tremendous amount of work on this, so my first suggestion is going to be to elevate his privileges to help manage the code base and releases. With his agreement of course.

**Comment by sebcaps** [comment]
So sad to see what happens to such open source initiative that definitely promote their tool (without any financial impact for contributors).

I guess removing Postman reference (both in word and image) would be enough.

Personnaly I do not use this plugin anymore and just continue contributing to help community and for personal challenge. Very disappointed. :-(

I need to think a little bit more about this before taking a decision regarding my next contribution(s).

@carlowahlstedt  sorry for the inconvenience, when using this plugin it was really a great tool and was happy to help.

**Comment by Scott-Emberson** [comment]
I am happy to help where I can. 
What about calling it P0stm@n API

**Comment by Scott-Emberson** [comment]
So what're our next steps @carlowahlstedt  to get this back onto the Market place with the new version?

**Comment by carlowahlstedt** [comment]
Well, I actually had postman reach out and I thou they were going to all us to keep going but I haven’t heard back. I'll touch base with them again next week.

**Comment by AndeyR** [comment]
Can I install it in DevOps now..somehow?

**Comment by carlowahlstedt** [comment]
ok, awesome news. After working with Postman and Microsoft the most recent changes have been pushed to the Marketplace! We can now continue this project. I'll be working to catch up on other issues and PRs over the coming weeks. 
![image](https://user-images.githubusercontent.com/2687687/58876229-70152e80-869b-11e9-8ce0-1dd1c912024c.png)
