### ISSUE TITLE
Add the ability to print htmlextra console logs

### ISSUE THREAD

**Issue by yossarian123** [carlowahlstedt/NewmanPostman_VSTS_Task#63]
htmlextra added the ability to include postman console.log statements using the --reporter-htmlextra-logs flag.  This should be added as an additional flag as it prints a lot of useful information while debugging. 

https://www.npmjs.com/package/newman-reporter-htmlextra

**Comment by yossarian123** [comment]
I have this on a branch but I'm not able to push it - do I need any additional permissions for the repo?

**Comment by carlowahlstedt** [comment]
If you forked the repo you should be able to create a PR from your repo to this one. Others had done it successfully recently.
