### ISSUE TITLE
Collection File Source option always fails

### ISSUE THREAD

**Issue by realfaisalk** [carlowahlstedt/NewmanPostman_VSTS_Task#67]
Hi,
I am using the task in an Azure pipeline and have collection, global and environment json files. Newman npm is being installed correctly.
When the Newman task comes to run it always fails with the following error: "##[error]Could not find any collection files in the path provided"
Note: I have tried different pattern matching to point to the file but nothing works.
I know that the Newman cli is now on **v4.5.1** whereas as the task is **v3**, could this be the issue?
![image](https://user-images.githubusercontent.com/23498757/60016356-e515cb80-967d-11e9-8fe8-114d2d6743aa.png)
![image](https://user-images.githubusercontent.com/23498757/60016442-1bebe180-967e-11e9-9551-609c0d475343.png)

**Comment by carlowahlstedt** [comment]
To clarify, this task doesn't specify the version of newman that you run. What you install on the server does that. It is a coincidence that the task is v3 and newman was recently updated to v4.

That said, While I maintain this task, I don't really use the task. I really want to setup some scenarios to actually use it, but haven't had/made that time. You can look [at some sample releases](https://dev.azure.com/carlo/VSTS_Tasks/_releaseDefinition?definitionId=5&_a=definition-tasks&environmentId=5) I started creating at some point, but they don't actually DO anything. I'd love to get someone to create some sample releases that people could really look at to learn from.

However, it looks to me like you're using ./ where I would recommend the **/ pattern:
![image](https://user-images.githubusercontent.com/2687687/60313186-203d2680-992c-11e9-9248-9c468390d077.png)
You should have more success matching on that.
