### ISSUE TITLE
Unable to select junit report

### ISSUE THREAD

**Issue by sandrabn** [carlowahlstedt/NewmanPostman_VSTS_Task#69]
When creating a new Newman task, I am not able to select any report. I am only able to setup a path for the report. This way no report file is generated. 

The command that is currently executed: 
newman run "mypostman_collection.json"  --reporter-junit-export  "PATH_TO_REPORT\report.xml" -n 1 --folder "Folder to run" -e "MY.postman_environment.json"

The part "**--reporters junit**" is missing from this command. 

The command that is expected: 
newman run "mypostman_collection.json"  --reporters junit --reporter-junit-export  "PATH_TO_REPORT\report.xml" -n 1 --folder "Folder to run" -e "MY.postman_environment.json"

![image](https://user-images.githubusercontent.com/47812909/61214656-c51b7a00-a708-11e9-98e9-7122c22fb779.png)

Is our version of VSTFS too old?

Running on
Microsoft Visual Studio Team Foundation Server
Version 15.117.27414.0

**Comment by carlowahlstedt** [comment]
Looks like you’re on [Team Foundation Server 2017](https://stackoverflow.com/questions/9473820/identifying-version-of-team-foundation-server). Which means 2 major updates behind the last I checked. I don’t have any on-prem setup to test with, but we have seen this similar issue reported previously. That’s the only conclusion I can come to is the old version of the server as compared to the js using for the extension. 

Is there any way you can update or request that your version get updated? Honestly, in my opinion, 2 major versions behind it at least 1 too many.

**Comment by sandrabn** [comment]
I totally agree with you: we are way behind with the TFS updates. 
Unfortunately, there is nothing I can do about that at the moment. If we ever update TFS, I will try this task again. 
Thanks for replying.
