### ISSUE TITLE
Uploading file with newman cli fails

### ISSUE THREAD

**Issue by nilfdev** [carlowahlstedt/NewmanPostman_VSTS_Task#71]
**Describe the bug**
Not possible to use formdata file on azure environment. 

**To Reproduce**
1. Create scenario for sending file
![image](https://user-images.githubusercontent.com/15476934/62380635-dc9c9480-b549-11e9-8c20-75d149593bf1.png)

2. Check the file does exist on build agent
![image](https://user-images.githubusercontent.com/15476934/62379709-c988c500-b547-11e9-817a-e9a4c41e9ffe.png)

3. Scenario is failed because file parameter doesn't contain data. File is empty. 

4. Execute the same scenario on local environment - it works. File is sent correctly.

5. For extra validation - it is possible to adjust the scenario to check if it starts execution: 
![image](https://user-images.githubusercontent.com/15476934/62380869-749a7e00-b54a-11e9-887a-2ec904b03873.png)
it this case file is missing and newman cli informs about it. 
![image](https://user-images.githubusercontent.com/15476934/62380907-8d0a9880-b54a-11e9-97e4-f111664b9669.png)

**Expected behavior**
It was working till today. make it possible to send file via newman cli
When you select file on remote environment - retrieve the file and send it. 

**Screenshots**

**Azure DevOps Version:**
 - Installation: Azure DevOps 
 - Task Version: 3+, 4+,
 - Command Log Output: [e.g. [command]C:\windows\system32\cmd.exe /D /S /C 

**Additional context**
Started failing from today.

**Comment by carlowahlstedt** [comment]
I notice you have a prepending / before c:/. It seems that might be throwing it off? There was an update pushed to the task Monday of this week, but nothing has changed since.

**Comment by nilfdev** [comment]
> I notice you have a prepending / before c:/. It seems that might be throwing it off? There was an update pushed to the task Monday of this week, but nothing has changed since.

this format is generated by default from postman. 
But, I tried with "/" before c:/ without "/". I also tried with anchor {{path}} and global variable parameter. The result is always the same. File is empty

**Comment by carlowahlstedt** [comment]
@nilfdev Sorry I haven't been more help here. I'm not sure I know how to help without having a setup that I can test and verify with.
