### ISSUE TITLE
Publish reports is not working 

### ISSUE THREAD

**Issue by saitejkuralla** [carlowahlstedt/NewmanPostman_VSTS_Task#72]
![File not found](https://user-images.githubusercontent.com/11627655/63849723-47f24e80-c9b0-11e9-8254-35c5f29e4207.PNG)

I was getting the below error 

Command used to genarate reports : newman run MyAutomationAPITesting.postman_collection.json -e Development.postman_environment.json --reporters cli,junit --reporter-junit-export TestResult/result-tests.xml 

Below is my publish results task

![image](https://user-images.githubusercontent.com/11627655/63849852-86880900-c9b0-11e9-9150-78d686669132.png)

**Comment by carlowahlstedt** [comment]
Are you sure that the test results files are being output into the directory you specified? Could you paste the log output from that to verify?

**Comment by roddaz** [comment]
Hello Just installed and having the same issue , I can confirm that the results file is generated  but getting the same "No Results Found to Publish" error
![Error](https://user-images.githubusercontent.com/50347061/68266603-6ceff580-00b4-11ea-8958-3d9528b19b0b.PNG)
![file](https://user-images.githubusercontent.com/50347061/68266657-914bd200-00b4-11ea-9892-291a68f292e8.PNG)
![content](https://user-images.githubusercontent.com/50347061/68266674-a32d7500-00b4-11ea-9b23-0d8cdb3773a5.PNG)

**Comment by carlowahlstedt** [comment]
@roddaz the path you're showing and the path to look for the xml files in the original post don't match. That's why it wouldn't find it in this case. Is that what your test results look like?

**Comment by roddaz** [comment]
@carlowahlstedt  Hey Carlo sorry the desktop scaling on my laptop is hopeless so highlight included the Azure task path.

I double checked and the path in the Publish task for the result file it found and can confirm that it is correct and the file exists at that location added some better screen shots to show this.
 
The path for the Newman-Postman task **Reporter JUnit Export** and **Publish Test results search folder** are both using the same Azure var $(System.DefaultWorkingDirectory) so match

![AzureTask](https://user-images.githubusercontent.com/50347061/68334754-234cec80-0140-11ea-85ae-8b5cbde20216.png)

![ResultFile](https://user-images.githubusercontent.com/50347061/68334776-2d6eeb00-0140-11ea-83ca-c84e37a5c429.png)

And yeah the last screen shot is what the generated XML looks like
![content](https://user-images.githubusercontent.com/50347061/68335265-06fd7f80-0141-11ea-85a2-07bb80850585.PNG)

I believe it is finding the file but parsing through it find no results?

Other than this it is working great :-)

**Comment by roddaz** [comment]
Hey @carlowahlstedt  found the issue user error..... the clue was in the junit result file apparently I didn't save the collection when I added some tests to it so it was running the request but there were no tests in it once I added a test and re-ran it is now working as expected.
Sorry and thanks fro your time
