### ISSUE TITLE
Iteration value is not updated based on the data file 

### ISSUE THREAD

**Issue by sandeepModaboyina** [carlowahlstedt/NewmanPostman_VSTS_Task#76]
**Iteration is not updated based on the data file **

**To Reproduce**
1. Go to 'Task'
2. Add a data file with more than 3 rows 
3. Check the Iteration Value 

**Expected behavior**
Should be it based on data file added ?

**Screenshots**
![image](https://user-images.githubusercontent.com/26226408/73275126-949bb900-41de-11ea-8d66-1479f7aa9ef1.png)

**Comment by carlowahlstedt** [comment]
I would not expect that an imported file would change the iteration. It is meant for you to update manually based on how any iterations you want.
