### ISSUE TITLE
newman cli run time can we use first api response to next as input while store in the variable 

### ISSUE THREAD

**Issue by Madhusudanpatidar** [carlowahlstedt/NewmanPostman_VSTS_Task#81]
**Describe the bug**
I have 3 api in the collection
first api response in have token
second api use first api token as input & generate response in one of the dataid
third api use the second api response in data id as input and response is comming

The the three api is only GET request
 using postman 3 are working individually 
but using newman cli to run postman collection and global variable on command prompt
so its not working
bcz api is depends eatch other and run time token and data is generated

**Comment by sebcaps** [comment]
Does your test runs correctly on postman IDE ? Do you specify path to var files ? Do you export them ?

**Comment by Madhusudanpatidar** [comment]
> Do your tests run correctly on postman IDE ? Do you specify path to var files ? Do you export them ?

yes i have specify path and vae files and also export them...
but run time response is pass to new api is not working on newman cli

**Comment by carlowahlstedt** [comment]
Without more clear steps I'm afraid we can't help you here. This sound like a setup or pipeline issue and not a specific issue with the postman task.
